---
abstract: 'Plugin based Status Badge generator'
author:
  - 'André Rivotti Casimiro <rivotti@cpan.org>'
build_requires:
  File::Spec: 0
  IO::Handle: 0
  IPC::Open3: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.029, CPAN::Meta::Converter version 2.142060'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WWW-StatusBadge
requires:
  perl: 5.010
resources:
  bugtracker: https://github.com/ARivottiC/WWW-StatusBadge.pm/issues
  homepage: https://github.com/ARivottiC/WWW-StatusBadge.pm
  repository: https://github.com/ARivottiC/WWW-StatusBadge.pm.git
version: 0.0.1
